version: '3.9'

services:
  db-numer:
    image: mysql:9
    container_name: numer-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: numerical-method
      MYSQL_USER: guess
      MYSQL_PASSWORD: guess
    ports:
      - "3306:3306"
  # db-numer-client:
  #   image: phpmyadmin
  #   container_name: numer-db-client
  #   restart: always
  #   depends_on:
  #     - db-numer
  #   ports:
  #     - "8081:80"
  #   environment:
  #     - PMA_ARBITRARY=1
  # server:
  #   build:
  #     context: ../...
  #     dockerfile: ../backend/.
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db-numer
    