version: '3.9'

services:

  db-numer:
    image: mysql:8
    container_name: numer-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: numerical-method
      MYSQL_USER: guess
      MYSQL_PASSWORD: guess
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: numer-backend
    restart: always
    environment:
      - SERVER_PORT=8080
      - DSN=root:root@tcp(db-numer:3306)/numerical-method?charset=utf8mb4&parseTime=True
    ports:
      - "8080:8080"
    depends_on:
      - db-numer

  frontend:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: numer-frontend
    restart: always
    environment:
      - VITE_API_URL=http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
    