info:
  contact: {}
paths:
  /api:
    get:
      consumes:
      - application/json
      description: Initializes the root of equations and linear algebra controllers
      produces:
      - application/json
      responses: {}
      summary: Set up API controllers
      tags:
      - Setup
swagger: "2.0"
